### ISSUE TITLE
Issue executing callAs400 on PcmlDao

### ISSUE THREAD

**Issue by alexmacavei** [dweibel/pcml-om#1]
Hey,

First of all, thanks for the awesome tooling!

My issue is the following:

``` java
private static final AS400 mysystem = new AS400("system", "username", "password");
...
PcmlDao program = new PcmlDao("PROGR", classLoader, "xmlmapper", classLoader);
program.callAs400(mysystem, programName, new Object[]{ item1, item2, item3 });
```

Getting compile-time error on mysystem at callAs400 call.

```
'callAs400(AS400, java.lang.String, java.lang.Object...)' in 'org.pcml_om.PcmlDao' cannot be applied to '(com.ibm.as400.access.AS400, java.lang.String, java.lang.Object[])'
```

I'm using JTOpen 8.4.

Thanks for any help,
Alex

**Comment by alexmacavei** [comment]
Managed to go through this by recompiling pcml-om locally with 8.4 JTOpen dependency and repackaging.

**Comment by dweibel** [comment]
Hi,

I've made substantial improvements since putting this code on github.  I
didn't bother updating it because nobody else seemed to be using it.  I'll
try to update the project in a few days.  I can send you a zipped copy of
the current code tonight.

**Comment by alexmacavei** [comment]
Hi,

Yes I've noticed people are not using it and it's really puzzling me. I've come up on it accidentally and it sounded really like something awesome.

It would be great if you could update the code on here, or send me an updated version through e-mail. If it's no trouble to you, of course. 

There's one more thing I encountered when building my PcmlDao object. But I'll open a new issue with that. Maybe this was also solved in your working code but I'll create the issue nonetheless as this great tooling needs more activity :-) 

Thanks very much Dirk,
Alex
